import csstype.*
import emotion.react.css
import react.FC
import react.Props
import react.dom.html.ReactHTML.div
import react.dom.html.ReactHTML.p
import theme.Colors

external interface ContentProps : Props {

}

val Content = FC<ContentProps> {
    div {
        css {
            height = 100.pct
            maxHeight = 100.pct
            fontSize = 2.vmin
            paddingLeft = 2.vmin
            paddingRight = 2.vmin
            overflowY = Overflow.scroll
            backgroundColor = Colors.black
            color = Colors.white
        }
        p { +"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget tincidunt tellus. Nulla euismod orci eget enim tempor, non varius est hendrerit. In at aliquam libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sollicitudin purus purus, non vestibulum leo vestibulum eu. Donec vitae aliquet turpis. Donec ac fermentum sapien. Phasellus consequat luctus nibh." }
        p { +"Etiam iaculis faucibus eros, sed porta tellus finibus non. Ut non tellus ultricies, faucibus ipsum nec, pretium mi. Aliquam efficitur varius consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sit amet arcu vitae leo egestas maximus. Nulla dignissim tincidunt nisl a aliquet. Praesent sollicitudin volutpat nulla, sit amet porta est dapibus sit amet. Vivamus rhoncus odio a congue pharetra. Nullam sed massa neque. Nullam ac cursus lectus, at gravida metus. In vitae ipsum vitae quam egestas congue. Vivamus at quam orci. Nullam vitae turpis purus. Aenean facilisis ex eget venenatis laoreet. Phasellus posuere vitae massa et venenatis." }
        p { +"Integer finibus pulvinar elit lacinia porttitor. Vivamus at sapien vel metus feugiat egestas non a diam. Curabitur sed purus blandit massa placerat placerat. Suspendisse imperdiet est sit amet tortor hendrerit, eget vulputate elit egestas. Vestibulum gravida tellus augue. Nam euismod quis tellus eget ullamcorper. Aenean vestibulum, lacus ac porttitor rutrum, ipsum enim dictum eros, ac lacinia felis est eget orci. Nunc vestibulum sem quis ipsum iaculis, nec molestie eros bibendum. Quisque porttitor ex nisl. Aliquam vel libero rhoncus, iaculis lorem non, sodales tellus. Quisque nec viverra purus. Aenean convallis diam in odio dapibus, id dictum est convallis." }
        p { +"Nullam hendrerit semper pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce quis arcu id neque elementum dignissim nec id ante. Mauris sit amet tortor elit. Pellentesque viverra vitae orci sit amet dignissim. Maecenas risus lorem, dapibus at elit porta, porttitor egestas felis. Vivamus suscipit mi elit, egestas luctus libero sollicitudin ut. Etiam sit amet justo urna. Aenean varius dolor eu laoreet fermentum. Proin ultricies elit ex, viverra faucibus dolor pellentesque nec. In eu ullamcorper est." }
        p { +"Nullam ullamcorper erat vel mi gravida elementum. Integer at justo vel magna ultricies finibus posuere eu erat. Quisque lacinia aliquet quam pretium laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam vulputate, neque sit amet faucibus aliquet, nisi turpis convallis neque, eu egestas quam augue nec enim. Vestibulum eleifend non tortor vel fringilla. Morbi malesuada luctus justo, at hendrerit mauris convallis ut. Integer dapibus, ex eget suscipit semper, odio eros bibendum orci, sed pharetra arcu mi eu enim. Nam at sapien tortor. Vivamus auctor felis nec neque viverra, nec aliquet lorem gravida. Aenean nec accumsan mauris. Vestibulum id blandit eros, et fringilla dolor. Aliquam quis dui quis justo fringilla suscipit. Nulla facilisi. Sed viverra massa eget velit elementum euismod." }
        p { +"Donec consequat, nibh at scelerisque vulputate, mauris est mattis enim, in ullamcorper neque augue id lacus. Nam ut nisl augue. Quisque tortor risus, facilisis commodo dolor sed, venenatis tristique urna. Vestibulum accumsan aliquam enim, ac tempus lacus semper id. Integer lobortis dictum arcu sed tristique. Quisque consequat magna quis nunc porttitor, vitae efficitur libero viverra. Etiam pellentesque sodales lectus, tempor varius massa. Ut consectetur eget mauris vel iaculis. Donec accumsan urna est, ut interdum eros ultrices quis. Nulla pharetra tortor non eros consequat, ac elementum felis ultrices. Maecenas id euismod augue, sit amet volutpat elit. Curabitur finibus rutrum nisi, ut blandit urna aliquam at. Vivamus iaculis ut lorem ut vestibulum. Vestibulum nec vehicula dolor. Nam dapibus, purus facilisis ullamcorper placerat, elit lorem pharetra mauris, nec sodales lectus mauris quis nunc. Maecenas auctor tellus eget diam iaculis, ac sollicitudin lacus aliquet." }
        p { +"Vivamus leo ligula, efficitur pretium consequat quis, condimentum eget turpis. Maecenas et purus nec elit sodales fermentum. Nulla nec tellus rutrum, efficitur tellus eget, eleifend risus. Sed tincidunt auctor tellus scelerisque consectetur. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vel arcu nec diam porttitor porta eget eget est. Nullam suscipit scelerisque nisi. Vestibulum viverra libero et maximus pharetra. Nulla luctus commodo velit sit amet molestie. Pellentesque egestas nec purus sed sollicitudin. Vestibulum euismod urna pharetra arcu malesuada placerat. Integer mattis tincidunt arcu, et laoreet mi egestas dictum. In non eros tincidunt sapien iaculis ultrices. Aenean tincidunt dui eu elementum pretium." }
        p { +"Nunc blandit felis sed posuere condimentum. Praesent nisi nisi, iaculis sed orci eleifend, scelerisque hendrerit elit. Morbi eget mauris nec velit semper vestibulum. Donec dignissim ipsum nibh, aliquam vulputate velit pulvinar ut. Nullam ligula est, gravida egestas vulputate pharetra, laoreet sit amet orci. Vestibulum pellentesque faucibus nunc, id imperdiet turpis auctor quis. Vivamus id libero et nibh convallis vehicula. Nullam interdum fringilla ex, sit amet luctus est malesuada ac. Praesent cursus faucibus fermentum. Sed sollicitudin odio a pulvinar fringilla. Etiam imperdiet congue ultrices. Donec volutpat molestie nisl sed ultricies. In in velit eu diam tincidunt sollicitudin at et tortor. Sed pretium, metus ut pellentesque pharetra, arcu ante pulvinar tellus, quis pretium ex tortor id elit. Vivamus placerat sapien sapien, sit amet porttitor nisl laoreet a." }
        p { +"Etiam nec enim efficitur, dapibus nisi eu, rutrum dui. Nunc at turpis mattis, tempus orci vulputate, maximus quam. Vivamus egestas, nibh blandit auctor hendrerit, sapien elit dapibus sapien, quis facilisis orci turpis id nunc. Vestibulum sit amet fermentum neque. Duis dapibus nibh nec risus venenatis, vel venenatis leo vehicula. Vestibulum pellentesque mauris a massa molestie, eu laoreet neque tincidunt. Maecenas et consequat ligula. Aenean non mollis mi. Quisque egestas sem et lacus vehicula, at ullamcorper magna maximus." }
        p { +"Nulla felis tellus, ullamcorper vitae dignissim vel, cursus quis lorem. Pellentesque commodo commodo efficitur. Phasellus vel mi augue. Integer scelerisque ultricies lectus quis finibus. Phasellus in lacus id mi ornare iaculis a vel risus. Vestibulum laoreet ante enim, tincidunt volutpat eros sodales quis. Nunc neque est, consectetur non commodo quis, interdum nec eros. Sed velit nunc, aliquet non tempor sed, porta sit amet nibh. Ut nibh neque, euismod id justo et, posuere porttitor justo. Suspendisse scelerisque mattis neque, ac congue neque eleifend vel. Nullam dignissim convallis tincidunt. Quisque porttitor tortor ac nunc lobortis imperdiet. Nulla ornare erat non mi ultrices, laoreet mattis urna finibus. Nam tempus tellus non ipsum dapibus molestie. Morbi porta felis justo, a sagittis metus suscipit vitae. Vivamus elementum lorem ut malesuada pulvinar." }
        p { +"Phasellus commodo mattis magna, quis porttitor tellus. Praesent et erat condimentum, dictum ipsum a, egestas est. In vulputate diam ligula, vitae egestas tellus blandit quis. Nulla non blandit orci, quis pharetra leo. Donec imperdiet tellus at tincidunt placerat. Nullam pretium faucibus leo, sit amet euismod ex lobortis nec. Nullam faucibus eleifend semper. Nunc blandit diam ac mauris ultrices, sit amet malesuada ipsum imperdiet. Proin tincidunt massa non nisl pulvinar tincidunt. Duis vitae quam porta, luctus ipsum quis, facilisis sapien. Donec molestie erat lacus, non mollis massa tempor vel. In dignissim sapien lacus, quis volutpat magna fringilla eu. Integer vitae sollicitudin dui, vitae suscipit sapien. Vivamus in neque vel erat convallis finibus ac sit amet dolor." }
        p { +"Proin id felis et dolor dignissim vehicula luctus a augue. Etiam sollicitudin elit sem, id commodo tellus pellentesque eu. Cras odio enim, dictum semper turpis id, venenatis faucibus odio. Quisque sollicitudin consectetur erat vel condimentum. Curabitur feugiat eleifend scelerisque. Duis sed hendrerit ipsum. Cras euismod dolor sem, et imperdiet elit tincidunt sed. Nulla a enim odio. Morbi lacus est, malesuada eget fermentum a, aliquet at nisl." }
        p { +"Phasellus vitae lorem metus. Nunc eleifend eros nulla, tincidunt cursus diam laoreet facilisis. Phasellus venenatis, ante id varius dapibus, ligula metus semper libero, eget efficitur dui lacus id nulla. Duis volutpat neque id porttitor vulputate. Quisque nec purus at justo tristique porttitor. Nullam at consectetur metus. Nulla ultricies aliquam metus in blandit." }
        p { +"Vestibulum semper tellus sit amet ultrices volutpat. Suspendisse feugiat, libero et auctor elementum, nunc odio sollicitudin purus, a vehicula lectus sem id neque. Fusce eleifend semper sem, in facilisis lacus commodo sit amet. Fusce pellentesque felis nec turpis porta, nec fermentum neque molestie. Mauris fringilla quis sapien nec auctor. Duis quis quam massa. Praesent sed nisl ultrices, rhoncus ex vel, blandit odio. Cras lacus tellus, pulvinar quis nisi vitae, euismod congue lectus. Morbi iaculis mauris vitae nunc vulputate, lobortis pulvinar ipsum venenatis. Aliquam venenatis ex arcu, a mollis nibh condimentum vel. Nullam lacinia sit amet lacus id blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus." }
        p { +"Integer porta, ipsum sed lacinia auctor, nunc sem scelerisque metus, quis feugiat elit ex ut nunc. Quisque id placerat purus. Quisque a varius massa. Nunc ornare porta fermentum. Donec eget turpis dictum tellus maximus varius congue sed orci. In aliquam rhoncus eros. Pellentesque pulvinar enim ac nulla congue, quis vestibulum ligula faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ornare eget lacus non fermentum." }
    }
}
